### PR TITLE
Use API instead of S3 to get the current dataset .zip

### PR DESCRIPTION
**Pull request by zygmuntz**
Implementing https://github.com/numerai/submission-criteria/issues/36

### CODE REVIEW

**Comment by xanderdunn** [comment]
This is a great start, thanks!  Please remove the `download_dataset` function in 3_util.py since it isn't used anymore.

**Comment by xanderdunn** [comment]
Also, although it works, it's not a good idea to use the testing_api.py to get the production dataset.  That file has special behavior for the unit and integration tests.

Instead, add [numerapi](https://github.com/uuazed/numerapi) as a dependency and import it with `from numerapi.numerapi import NumerAPI`.

**Comment by zygmuntz** [comment]
Done that. The CI test is failing, I don't know why. The details link is 404.

**Comment by xanderdunn** [comment]
Great, thanks!  CI doesn't pass only because this is a non-internal branch.  It's fine.  

Can you also add `numerapi` to the setup.py dependencies, and remove the `zipfile` import in s3_util.py since it isn't used anymore.  Than it should be good for merge.

**Comment by zygmuntz** [comment]
Sure thing.

**Comment by xanderdunn** [comment]
The linter has a nit-pick: Remove the `dest_path=` form this line:
https://github.com/numerai/submission-criteria/pull/56/files#diff-3481e7e91a5b7dd3985f325aa5f95e87R58

It's a positional argument, so it doesn't want a keyword.

If you have `pylint` installed, you can see the output of the linter using the command that's in the .circleci/config.yml:
```
find . -iname "*.py" ! -name "setup.py" ! -name "__init__.py" ! -path "./venv/*" | xargs pylint --rcfile=./.pylintrc
```

**Comment by zygmuntz** [comment]
OK

**Pull request closed without merging**
