### PR TITLE
Made a simple benchmark to test against out of the box models.

### PR DESCRIPTION
**Pull request by zoso95**

### CODE REVIEW

**Comment by zoso95** [comment]
I can make this a script if users aren't interested in notebooks

**Comment by philipcmonk** [comment]
Looks good to me.  I don't personally use notebooks, but I know many users do.  One thing I will insist on is  no spaces in filenames.

**Comment by cpurta** [comment]
It may be worth adding this as a script so it could be added as a part of a test suite.

**Comment by zoso95** [comment]
Ok, I changed the filename to not have any spaces. I will commit this so we have it in the test suite

**Pull request merged**
