### PR TITLE
Speed up originality by pre-sorting the submission

### PR DESCRIPTION
**Pull request by philipcmonk**
This was submitted by an anonymous contributor, and applies to #3.

Here's a demo of it:

```
import numpy as np
from scipy.stats import ks_2samp


def input_data(nusers=1000, nrows=4600, seed=0):
    rs = np.random.RandomState(0)
    submission = rs.rand(nrows)
    other_submission = rs.rand(nrows, nusers)
    return submission, other_submission


def run_originality(submission, other_submission):
    output = np.empty(other_submission.shape[1])
    for i in range(other_submission.shape[1]):
        x = originality_score(submission, other_submission[:, i])
        output[i] = x
    return output


# numerai's current implementation
def originality_score(submission1, submission2):
    return ks_2samp(submission1, submission2)[0]


# ---------------------------------------------------------------------------
# proposed speed up:

def run_originality2(submission, other_submission):
    output = np.empty(other_submission.shape[1])
    submission = np.sort(submission)
    for i in range(other_submission.shape[1]):
        x = originality_score2(submission, other_submission[:, i])
        output[i] = x
    return output


# this function is taken from scipy (ks_2samp) and modified and so falls
# under their BSD license
def originality_score2(data1, data2):
    data2 = np.sort(data2)
    n1 = data1.shape[0]
    n2 = data2.shape[0]
    data_all = np.concatenate([data1, data2])
    cdf1 = np.searchsorted(data1, data_all, side='right') / (1.0*n1)
    cdf2 = np.searchsorted(data2, data_all, side='right') / (1.0*n2)
    d = np.max(np.absolute(cdf1 - cdf2))
    return d


"""
demo

First check that the speed up gives the same results:

In [2]: submission, other_submission = input_data()
In [3]: originality = run_originality(submission, other_submission)
In [4]: originality2 = run_originality2(submission, other_submission)
In [5]: (originality == originality2).all()
Out[5]: True

Now test speed:

In [6]: timeit run_originality(submission, other_submission)
1 loop, best of 3: 929 ms per loop
In [7]: timeit run_originality2(submission, other_submission)
1 loop, best of 3: 636 ms per loop

Speed up is over 30%:

In [8]: (929 - 636) / 929.0
Out[8]: 0.3153928955866523
"""
```

### CODE REVIEW

**Comment by zoso95** [comment]
Did you check correctness on the version being committed? The psudeocode in the description makes sense for why it works, but the code being commit seems a bit stranger that it works...

**Comment by philipcmonk** [comment]
I tested the demo at the bottom of this, which emprically suggests it's the same.

```
import numpy as np
from scipy.stats import ks_2samp


def input_data(nusers=1000, nrows=4600, seed=0):
    rs = np.random.RandomState(0)
    submission = rs.rand(nrows)
    other_submission = rs.rand(nrows, nusers)
    return submission, other_submission


def run_originality(submission, other_submission):
    output = np.empty(other_submission.shape[1])
    for i in range(other_submission.shape[1]):
        x = originality_score(submission, other_submission[:, i])
        output[i] = x
    return output


# numerai's current implementation
def originality_score(submission1, submission2):
    return ks_2samp(submission1, submission2)[0]


# ---------------------------------------------------------------------------
# proposed speed up:

def run_originality2(submission, other_submission):
    output = np.empty(other_submission.shape[1])
    sorted_submission = np.sort(submission)
    for i in range(other_submission.shape[1]):
        x = originality_score2(sorted_submission, other_submission[:, i])
        output[i] = x
    return output


# This function is taken from scipy (ks_2samp) and modified and so falls
# under their BSD license
def originality_score2(data1, data2):
    """
    Computes the Kolmogorov-Smirnov statistic on 2 samples.

    This is a two-sided test for the null hypothesis that 2 independent samples
    are drawn from the same continuous distribution.

    Warning: data1 is assumed sorted in ascending order.

    Parameters
    ----------
    data1, data2 : ndarray
        Two arrays of sample observations assumed to be drawn from a
        continuous distribution. Arrays must be of the same size. data1 is
        assumed sorted in ascending order.

    Returns
    -------
    statistic : float
        KS statistic
    """

    # data1 is assumed sorted in ascending order
    data2 = np.sort(data2)
    n1 = data1.shape[0]
    n2 = data2.shape[0]
    if n1 != n2:
        raise ValueError("`data1` and `data2` must have the same length")

    # the following commented out line is slower than the two after it
    # cdf1 = np.searchsorted(data1, data_all, side='right') / (1.0*n1)
    cdf1 = np.searchsorted(data1, data2, side='right')
    cdf1 = np.concatenate((np.arange(n1) + 1, cdf1)) / (1.0*n1)

    # the following commented out line is slower than the two after it
    # cdf2 = np.searchsorted(data2, data_all, side='right') / (1.0*n2)
    cdf2 = np.searchsorted(data2, data1, side='right')
    cdf2 = np.concatenate((cdf2, np.arange(n1) + 1)) / (1.0*n2)

    d = np.max(np.absolute(cdf1 - cdf2))

    return d


"""
demo

First check that the speed up gives the same results:

In [2]: submission, other_submission = input_data()
In [3]: originality = run_originality(submission, other_submission)
In [4]: originality2 = run_originality2(submission, other_submission)
In [5]: (originality == originality2).all()
Out[5]: True

Now test speed:

In [6]: timeit run_originality(submission, other_submission)
1 loop, best of 3: 903 ms per loop
In [7]: timeit run_originality2(submission, other_submission)
1 loop, best of 3: 505 ms per loop

Speed up is 44%:

In [8]: (903 - 505) / 903.0
Out[8]: 0.4407530454042082
"""
```

**Comment by zoso95** [comment]
We should also consider using this KS test for concordance as well. But that is less urgent.

**Comment by philipcmonk** [comment]
This satisfies both conditions of #3, so the entire 40 NMR bounty will be paid to the anonymous contributor.

**Pull request merged**
