### PR TITLE
Documentation

### LINKED ISSUE #1: Documentation
The README should give clear instructions for running the code, and should provide an overview of the code structure.

~~Each file should have a docstring, and most functions as well.  Particular attention should be paid to the originality, concordance, and consistency checks.~~

~~This issue has a 20 NMR bounty.~~

After #11, this issue has an 8 NMR bounty remaing.

### PR DESCRIPTION
**Pull request by cpurta**
Added docstring to all of the python files and most of the methods. Mostly focused on concordance and originality. Tried to determine the data types that are being used to the best of my knowledge.

Resolves #1

### CODE REVIEW

**Comment by philipcmonk** [comment]
This looks pretty good.  I'm going to look at it more closely, and get @zoso95 to review it as well.  It looks like this covers the majority what's described in #1.  What's missing is instructions for running the code, as well as a high-level description of the code base (both probably in `README.md`).

If you can supply those, you will receive the entire bounty.  Otherwise, since this covers the majority of the task, I will merge it and you will receive 12 NMR, and the remaining 8 NMR will go to whoever can complete the remainder of the task.  All of this is pending my and @zoso95's review (and potentially requested changes), of course.

**Comment by philipcmonk** [comment]
I'm going to merge this now.  @cpurta, can you let me know your username on numer.ai, so that I may send the 12 NMR?  If you would like to complete the rest of the documentation, you may earn the additional 8 NMR.

**Comment by cpurta** [comment]
@philipcmonk sounds great. My username is cpurta. Currently working on updating the README to have the rest of what was ask for in #1

**Comment by philipcmonk** [comment]
Great.  The 12 NMR should be in your account.

Thanks so much for contributing!

**Pull request merged**
